### ISSUE TITLE
Optional closing status bar prompt

### ISSUE THREAD

**Issue by luoluoqixi** [JonasDoesThings/obsidian-hide-folders#13]
Optional closing status bar prompt
![IMG_5356](https://github.com/JonasDoesThings/obsidian-hide-folders/assets/59384810/21f5efca-57b9-4647-9521-d4e6f14e4a36)

**Comment by JonasDoesThings** [comment]
Hi, sadly I do not understand fully. 
Do you want a setting to hide the "Configured folders are hidden" status-bar in the bottom?

**Comment by luoluoqixi** [comment]
Yes, because it is a little big in the phone, I hope to hide this prompt through the configuration.

(Sorry, my English is not good. I use translation software.)

**Comment by JonasDoesThings** [comment]
Gotcha! Sounds like a good idea, I will work on this in the coming days when I have time :)

**Comment by luoluoqixi** [comment]
Thanks!

**Comment by JonasDoesThings** [comment]
I have released version 1.5.0 of the plugin that adds a setting to hide the status bar text.

Please tell me if you notice any problems with that @luoluoqixi 
Greetings from Austria :)

**Comment by luoluoqixi** [comment]
Great, it works perfectly
