### ISSUE TITLE
Hide individual files in addition to folders?

### ISSUE THREAD

**Issue by kitschpatrol** [JonasDoesThings/obsidian-hide-folders#17]
Thanks for this plugin!

This is more of a request than a bug:

I have a few configuration files in the root of my vault (`sortspec`, `prettierrc`, that sort of thing) that I can't move into folders but which I'd like to hide from the file explorer view. This plugin does a great job hiding folders, but I noticed that it can't seem to hide these individual files even if their paths are added to the "Folders to hide" list.

I realize "folder" is right there in the name of plugin, but might be nice to be able to hide files as well.

**Comment by JonasDoesThings** [comment]
Not a bad idea! Should be possible with pretty much the same logic, for configuring I will probably add a `file:` prefix or something like that. Will look into it when I have time :)

**Comment by JonasDoesThings** [comment]
Hi, are you using the default file explorer? I just tried it out any my Obsidian only shows a selected list of type types anyways like (obviously .MDs) and .PDFs. 

Files with a .js ending, or no ending at all, don't get shown at all in the File Tab for me.

**Comment by kitschpatrol** [comment]
Aha good thought — I'm not using a custom file explorer, but I do have Obsidian's "Detect all file extensions" setting checked:

![Screenshot 2024-09-26 at 13 46 35 of Obsidian - Welcome - Test - Obsidian v1 6 7@2x](https://github.com/user-attachments/assets/4be7f623-7368-4d93-98a4-c4cb713adfcb)

For now I've switched to [File Hider](https://github.com/Oliver-Akins/file-hider) which does seem to hide individual files regardless of the all extensions setting — but I do miss the feature in your implementation that syncs hidden files to the exclusions list.

**Comment by JonasDoesThings** [comment]
Ahh didn't know about that setting!

If you include the file endings and not just the name, it should work:
![image](https://github.com/user-attachments/assets/d2788a1c-2b45-4b8c-b0ed-a9aedc57f1f1)

https://github.com/user-attachments/assets/206304f0-d193-4f00-acf7-80a8aab0cfad

**Comment by kitschpatrol** [comment]
You're absolutely right, I'm not sure why I hadn't added the file extensions in the exclusion list. Works now!

Thanks for the investigation.
