### ISSUE TITLE
[FR]: Add prefix

### ISSUE THREAD

**Issue by Lisandra-dev** [JonasDoesThings/obsidian-hide-folders#3]
Hello!
It's nice you added suffixe, but I would like to suggest "startswith". For example, all my attachment folder startswith `_`!

**Comment by JonasDoesThings** [comment]
Sorry for the late reply, had a busy workweek.

While typing out why imo it wasn't easily possible with the current technique used, I noticed that it should be easily doable, I just had a problem in my thinking - haha.

I should be able to put out a release containing this feature out tomorrow, thanks for the feedback :)

**Comment by JonasDoesThings** [comment]
Released v1.2.0 now which includes the `startsWith::` selector :) 
Feel free to report back any issues that may arise, thank you for your feedback!
