### ISSUE TITLE
Bug: Folders are only (un)hidden after refresh

### ISSUE THREAD

**Issue by tdnzr** [JonasDoesThings/obsidian-hide-folders#4]
After adding or removing a folder from the list of what to hide, folders aren't immediately (un)hidden. From what I can tell, folders are only hidden once you navigate to a new file or folder or something; and I couldn't find a way to unhide unlisted folders until I restarted Obsidian.

**Comment by JonasDoesThings** [comment]
Good catch :) 
I had a busy workweek, but was able to quickly fix this behaviour now. 

Fixed in version 1.1.1 which is released now :)
