### ISSUE TITLE
files disappeared for using a while [bug]

### ISSUE THREAD

**Issue by srun007** [JonasDoesThings/obsidian-hide-folders#6]
when used the plugin for a while , the files in obsidian explore could not see , but it would come back again after reload app.

obsidian : 1.4.16
plugin: 1.2.0 

![53c8e0391b3b08a240dd984bd55f591](https://github.com/JonasDoesThings/obsidian-hide-folders/assets/80263694/cc75f5b7-ebef-4adc-8138-1cd7a95857fa)
![26d738fd466e934ef7e1836eb38e75c](https://github.com/JonasDoesThings/obsidian-hide-folders/assets/80263694/e5e7a791-b747-4e1f-9b78-c32456d672cf)

**Comment by JonasDoesThings** [comment]
Should be fixed with version 1.2.1 🥳 
Please reopen if it persists.
