### ISSUE TITLE
Lack of compatibility with quick-explorer plugin

### ISSUE THREAD

**Issue by ivensrocha** [JonasDoesThings/obsidian-hide-folders#9]
Hey there,

One thing that I noticed is that this plugin doesn't work well with Quick Explorer. It keeps showing all files, even the excluded ones (Files and links settings). Do you think it is worth fixing?

See more details: https://github.com/pjeby/quick-explorer/issues/92

Thanks!

**Comment by JonasDoesThings** [comment]
Hmm, finally had time to look into this. 
Most I can do is hiding the folder from quick explorer, but I cannot change the numbers associated. Looks like this:
<img width="181" alt="image" src="https://github.com/JonasDoesThings/obsidian-hide-folders/assets/5180118/f26dd97b-cb51-474d-8228-1cba51a48f54">

So the hidden folder would be number 2 and is just missing in this example

**Comment by ivensrocha** [comment]
Yes, this is it. Perfect, thanks a lot :)

**Comment by JonasDoesThings** [comment]
Ok I FINALLY found some time & motivation to write a solution I am happy with. Had to do some hacking around the menu positioning of quick-explorer, but I think it finally works good enough 🙏 

To use it, you need to enable the experimental setting for it, it is disabled by default.
Let me know if you notice problems.

See v1.4.0 changelog regarding where to find the new experimental setting: https://github.com/JonasDoesThings/obsidian-hide-folders/releases/tag/1.4.0

**Comment by JonasDoesThings** [comment]
Gonna close it for now since it's released in the latet update. If you encounter any issues with the experimental feature in the new version feel free to either re-open this issue, or open a new one :)

Greetings from Austria
